name: Release minipp

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Package (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: minipp-linux-x86_64.tar.gz
          # Linux arm64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: minipp-linux-arm64.tar.gz
          # macOS x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: minipp-macos-x86_64.tar.gz
          # macOS arm64 (Apple Silicon)
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: minipp-macos-arm64.tar.gz
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: minipp-windows-x86_64.zip

    steps:
      - uses: actions/checkout@v4

      # 缓存 Rust 依赖，加速构建
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.87.0
          override: true
          target: ${{ matrix.target }}

      # 仅在交叉编译 Linux ARM64 时用 cross
      - name: Install cross
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: cargo install cross

      # 编译
      - name: Build (native/cross)
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi
        shell: bash

      # 打包
      - name: Prepare artifact
        run: |
          mkdir -p dist
          BIN_NAME=minipp
          TARGET_DIR=target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "Windows" ]]; then
            cp $TARGET_DIR/$BIN_NAME.exe dist/
            7z a dist/${{ matrix.artifact }} dist/$BIN_NAME.exe
          else
            cp $TARGET_DIR/$BIN_NAME dist/
            tar -czvf dist/${{ matrix.artifact }} -C dist $BIN_NAME
          fi
        shell: bash

      # 上传产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/${{ matrix.artifact }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.tar.gz,./artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}